spring:
  data:
    mongodb:
      uri: mongodb://clinicdb:27017/clinicdb
  # rabbitmq:
  #   host: rabbitmq
  #   port: 5672
  #   username: guest
  #   password: guest
  security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://users-service/users/.well-known/jwks.json

# queue:
#   name: name
  
springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Servico de consultas e prontuarios.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Medio

