spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clinic_service
          uri: http://clinic_service:8001
          predicates:
            - Path=/clinic/**
          filters:
            - name: CircuitBreaker
              args:
                name: clinicService
                fallbackUri: forward:/fallback/clinic
        - id: users-service
          uri: http://users_service:8002
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: usersService
                fallbackUri: forward:/fallback/users
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka_service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin_service:9411/api/v2/spans