spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clinic-service
          uri: lb://clinic-service
          predicates:
            - Path=/clinic/**
          filters:
            - name: CircuitBreaker
              args:
                name: clinicService
                fallbackUri: forward:/fallback/clinic

        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: usersService
                fallbackUri: forward:/fallback/users
