spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clinic-service
          uri: lb://clinic-service
          predicates:
            - Path=/clinic/**
          filters:
            - name: CircuitBreaker
              args:
                name: clinicService
                fallbackUri: forward:/fallback/clinic

        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: usersService
                fallbackUri: forward:/fallback/users
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://users-service/.well-known/jwks.json
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
 