spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clinic_service
          uri: http://clinic-service:8001
          predicates:
            - Path=/clinic/**
          filters:
            - name: CircuitBreaker
              args:
                name: clinicService
                fallbackUri: forward:/fallback/clinic
        - id: users-service
          uri: http://users-service:8002
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: usersService
                fallbackUri: forward:/fallback/users
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans