spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: clinic-service
              uri: http://clinic-service
              predicates:
                - Path=/clinic/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: clinicService
                    fallbackuri: forward:/fallback/clinic

            - id: users-service
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: usersService
                    fallbackuri: forward:/fallback/users
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://users-service/users/.well-known/jwks.json
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
 