server:
  port: 8001
  servlet:
    context-path: /users/

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/users
    username: users
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    format-sql: true
  sql:
    init:
      data-locations: classpath:data.sql
  # rabbitmq:
  #   host: rabbitmq
  #   port: 5672
  #   username: guest
  #   password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/users/.well-known/jwks.json
  
# queue:
#   name: name

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  name: Servico de usuarios.
  author: Jardel S. Oliveira
  mail: jardeloliver197@gmail.com
  severity: Alto